# Site
name: 'Masuk Internet'
description: 'Media informasi terkini.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'julaiman-web-id'
email: 'letakwebid@gmail.com'
mailchimp-list: 'https://gmail.us14.list-manage.com/subscribe/post?u=5f25916de47b43c1cfbec2588&amp;id=4b7ae81094&amp;f_id=0038b7e5f0'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Julaiman
      site:           https://julaiman.web.id
      avatar:         /masukinternet.github.io/assets/images/avatar1.png
      bio:            "Web Developer & Digital Marketing"
      email:          letakwebid@gmail.com
      twitter:        https://twitter.com/masjulaiman

    jane:
      name:           Nur
      site:           https://www.nurmusiani.blogspot.com
      avatar:         /masukinternet.github.io/assets/images/avatar2.png
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          nurmusiani37@gmail.com
      twitter:        https://twitter.com/nur
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Julaiman
      avatar: /masukinternet.github.io/assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
